# Generated by Django 3.1.8 on 2021-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default='123 mainstreet', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_zip_code',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='end_suspension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='onetime_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_suspension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup_day',
            field=models.CharField(default='saturday', max_length=50),
            preserve_default=False,
        ),
    ]
