# Generated by Django 3.1.8 on 2021-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210630_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
