# Generated by Django 3.1.8 on 2021-07-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='zip_code',
            new_name='employee_zip_code',
        ),
    ]
