# Generated by Django 3.1.8 on 2021-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210705_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
